export const SourceReservoirConditionDataSchema = {
  type: 'object',
  properties: {
    accumulaterainfallincatchment: { type: 'number' },
    desiltingtunneloutflow: { type: 'number' },
    drainagetunneloutflow: { type: 'number' },
    effectivewaterstoragecapacity: { type: 'number' },
    inflowdischarge: { type: 'number' },
    observationtime: { type: 'string' },
    othersoutflow: { type: 'number' },
    poweroutletoutflow: { type: 'number' },
    predeterminedcrossflow: { type: 'number' },
    predeterminedoutflowtime: { type: 'string' },
    reservoiridentifier: { type: 'number' },
    spillwayoutflow: { type: 'number' },
    statustype: { type: 'number' },
    totaloutflow: { type: 'number' },
    waterdraw: { type: 'number' },
    waterlevel: { type: 'number' },
  },
  required: [
    'accumulaterainfallincatchment',
    'desiltingtunneloutflow',
    'drainagetunneloutflow',
    'effectivewaterstoragecapacity',
    'inflowdischarge',
    'observationtime',
    'othersoutflow',
    'poweroutletoutflow',
    'predeterminedcrossflow',
    'predeterminedoutflowtime',
    'reservoiridentifier',
    'spillwayoutflow',
    'statustype',
    'totaloutflow',
    'waterdraw',
    'waterlevel',
  ],
} as const;

export const SourceDailyOperationalStatisticsOfReservoirSchema = {
  type: 'object',
  properties: {
    crossflow: { type: 'number' },
    capacity: { type: 'number' },
    outflow: { type: 'number' },
    outflowdischarge: { type: 'number' },
    outflowtotal: { type: 'number' },
    regulatorydischarge: { type: 'number' },
    reservoiridentifier: { type: 'string' },
    reservoirname: { type: 'string' },
    latestwaterdata: SourceReservoirConditionDataSchema,
    basinrainfall: { type: 'string' },
    datetime: { type: 'string' },
    dwl: { type: 'string' },
    inflow: { type: 'string' },
    nwlmax: { type: 'string' },
  },
  required: [
    'crossflow',
    'capacity',
    'outflow',
    'outflowdischarge',
    'outflowtotal',
    'regulatorydischarge',
    'reservoiridentifier',
    'reservoirname',
    'basinrainfall',
    'datetime',
    'dwl',
    'inflow',
    'nwlmax',
  ],
} as const;
